######################################################################
# Automatically generated by qmake (3.0) Mon Jan 29 15:20:27 2018
######################################################################

TEMPLATE = app
TARGET = MVC_QT
INCLUDEPATH += /usr/include/qt5/QtWidgets 
QT += sql

# Input
HEADERS += widget.h
SOURCES += main.cpp widget.cpp
